using System.ComponentModel.DataAnnotations;

namespace ProgressPath.Models;

/// <summary>
/// Represents a learning group created by a teacher.
/// Students join groups via QR code/join code to work toward a learning goal.
/// </summary>
public class Group
{
    /// <summary>
    /// Primary key identifier.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Display name of the group (e.g., "A2 - quadratic equations 1").
    /// Does not need to be unique.
    /// </summary>
    [Required]
    [MaxLength(100)]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Unique alphanumeric join code (6-8 characters) used in QR codes.
    /// Format: {BaseUrl}/join/{JoinCode}
    /// </summary>
    [Required]
    [StringLength(8, MinimumLength = 6)]
    public string JoinCode { get; set; } = string.Empty;

    /// <summary>
    /// Teacher's description of the learning goal in English.
    /// Maximum 500 characters per REQ-GROUP-004.
    /// </summary>
    [Required]
    [MaxLength(500)]
    public string GoalDescription { get; set; } = string.Empty;

    /// <summary>
    /// Type of goal: Binary (completed/not completed) or Percentage (progress bar).
    /// Determined by AI interpretation.
    /// </summary>
    public GoalType GoalType { get; set; }

    /// <summary>
    /// Number of discrete steps for percentage goals.
    /// Must be at least 2 for Percentage goals (REQ-GOAL-005).
    /// Null for Binary goals or before AI interpretation.
    /// </summary>
    public int? TotalSteps { get; set; }

    /// <summary>
    /// JSON string containing the AI's interpretation of the goal.
    /// Includes step definitions and other interpretation details.
    /// </summary>
    public string? GoalInterpretation { get; set; }

    /// <summary>
    /// Whether the teacher has confirmed the AI's goal interpretation.
    /// Group is not joinable until this is true (REQ-GROUP-010).
    /// </summary>
    public bool IsConfirmed { get; set; } = false;

    /// <summary>
    /// Welcome message shown to students when they join (displayed in header).
    /// Contains the task list - generated by AI and approved by teacher.
    /// </summary>
    [MaxLength(1000)]
    public string? WelcomeMessage { get; set; }

    /// <summary>
    /// Initial guidance message that starts the conversation.
    /// This is the first AI message in the chat, prompting the student to begin the first task.
    /// </summary>
    [MaxLength(1000)]
    public string? InitialGuidance { get; set; }

    /// <summary>
    /// Foreign key to the teacher who created this group.
    /// </summary>
    public int TeacherId { get; set; }

    /// <summary>
    /// Timestamp when the group was created.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    // Navigation properties

    /// <summary>
    /// The teacher who created and owns this group.
    /// </summary>
    public User Teacher { get; set; } = null!;

    /// <summary>
    /// Student sessions in this group.
    /// </summary>
    public ICollection<StudentSession> StudentSessions { get; set; } = new List<StudentSession>();
}
