namespace ProgressPath.Models.DTOs;

/// <summary>
/// Represents the AI's interpretation of a teacher's goal description.
/// Used during group creation to determine goal type and discrete steps.
/// REQ-GROUP-006, REQ-GROUP-008
/// </summary>
public class GoalInterpretation
{
    /// <summary>
    /// The type of goal determined by AI analysis.
    /// Binary for single-completion goals, Percentage for multi-step goals.
    /// </summary>
    public GoalType GoalType { get; set; }

    /// <summary>
    /// Descriptions of each discrete step for percentage goals.
    /// For binary goals, this will contain a single step.
    /// Target: 2-10 steps for percentage goals (REQ-GOAL-003).
    /// </summary>
    public List<string> Steps { get; set; } = new();

    /// <summary>
    /// The welcome message to show students when they join the group.
    /// Generated by AI to explain the goal they need to achieve.
    /// </summary>
    public string WelcomeMessage { get; set; } = string.Empty;

    /// <summary>
    /// Gets the total number of steps.
    /// </summary>
    public int TotalSteps => Steps.Count;

    /// <summary>
    /// Creates an empty goal interpretation (for error cases).
    /// </summary>
    public static GoalInterpretation Empty => new()
    {
        GoalType = GoalType.Binary,
        Steps = new List<string>(),
        WelcomeMessage = string.Empty
    };
}
